# Chekator Blender tool model manifest
# typeCode=displayName
100=Фреза
110=Шаровая концевая фреза
111=Коническая шаровая фреза
120=Концевая фреза
121=Концевая радиусная фреза
130=Угловая фреза
131=Угловая радиусная фреза
140=Торцевая фреза
145=Резьбофреза
150=Боковая фреза
151=Дисковая пила
155=Фасочная фреза
156=Фасочная радиусная фреза
157=Гравировальная резьбовая фреза
160=Сверло-резьбофреза
200=Спиральное сверло
205=Твердосплавное сверло
210=Расточная оправка
220=Центровочное сверло
230=Зенковка
231=Цековка
240=Метчик
241=Чистовой метчик
242=Метчик Whitworth
250=Развертка
500=Черновой токарный резец
510=Чистовой токарный резец
520=Канавочный резец
530=Отрезной резец
540=Резьбовой резец
550=Круглая пластина
560=Сверло в патроне
580=Токарный 3D-щуп
585=Калибровочный инструмент
700=Дисковая пазовая фреза
710=3D-щуп
711=Кромкоискатель
712=Одинарный щуп
713=Г-образный щуп
714=Звездчатый щуп
725=Калибровочный инструмент
730=Упор
731=Оправка
732=Люнет
900=Вспомогательный инструмент
